### ISSUE TITLE
Offset left error in all visualizations

### ISSUE THREAD

**Issue by b-stone** [b-stone/Visualize-M2#100]
We seem to have a common bug for all of our visualizations. I am getting the following error in the console.

```
Uncaught TypeError: Cannot read property 'offsetLeft' of null
```

**Comment by bbarwick** [comment]
I don't seem to get this error in Firefox on Ubuntu, but my guess is that it is coming from the following code:

`window.addEventListener("mousedown", function(e) {
      if (!menuOpen) return;
      tempMenu = document.getElementById("popupMenu");
      if ( (e.clientX < tempMenu.offsetLeft) || (e.clientY > tempMenu.offsetTop + tempMenu.offsetHeight) ) {
        tempMenu.style.display = "none";
        tempMenu.style.visibility = "hidden";
        menuOpen = false;
      }
    }, false);`

which can be safely deleted now that we are using the bootstrap side menu.  Check to see if it shows up for you when visualizing posets, since I believe I removed that code from the poset visualization template.

**Comment by bbarwick** [comment]
@b-stone I think pull request #115 should have fixed this issue.  Can you check?

**Comment by b-stone** [comment]
I don't get this error anymore. But a new error has come up in simplicial complexes. See Issue #110.
