### ISSUE TITLE
Errors when clicking Generate TikZ

### ISSUE THREAD

**Issue by b-stone** [b-stone/Visualize-M2#110]
I have an odd issue when I run the console. These errors occur when I click on the `Generate TikZ` code and then the clipboard button. 

![image](https://cloud.githubusercontent.com/assets/1364138/15635267/25158dbe-25a8-11e6-8858-a275589ff310.png)

Notice the reference file is the tmp file.

**Comment by b-stone** [comment]
this is meant for @bbarwick to look at

**Comment by bbarwick** [comment]
@b-stone I think pull request #115 should have fixed these console errors.  Can you check?

**Comment by b-stone** [comment]
So I think you solved this issue, but a new one is created with simplicial complex. See here:

![image](https://cloud.githubusercontent.com/assets/1364138/15651210/19acc95c-264c-11e6-98fc-fb85603e6d29.png)

The TIkZ works fine.

**Comment by bbarwick** [comment]
@b-stone Did you do something specific to make this error happen, or does it just happen when you open the example?  I don't seem to be getting this error in my version of Firefox.

**Comment by b-stone** [comment]
It happens when I load the file. First thing. It also happens in Safari

![image](https://cloud.githubusercontent.com/assets/1364138/15676945/384571dc-2716-11e6-81d4-72e552313dcd.png)

I tried it out in Firefox, but did not get the error. Can you check it out on Chrome? 

Maybe @vlandham can shed some light on this (please!!!).

**Comment by b-stone** [comment]
I should add that this error does not seem to effect the functionality. We might place a warning in the documentation though if it does not get resolved before M2 v 1.9.1.

**Comment by bbarwick** [comment]
I believe this issue is fixed now since pull request #119.  I was getting the same issue on Chrome.  I think the problem was that it was taking a little bit of time for the force layout to get started, and restart() was being run before the force layout initialized random points for the nodes, so it was trying to set the points for the polygons to be the (x,y) coordinates of the points, which were undefined before the force layout started.  I changed it to initialize all of the points for the polygons to start at (0,0).  This doesn't really make a difference visually because once the force layout starts (almost instantaneously) the vertices of the faces are automatically updated by the tick() function anyway.

@b-stone Could you check this on Safari and make sure it is actually fixed?

**Comment by b-stone** [comment]
Great. I just checked with chrome and safari. All good on my end.
