### ISSUE TITLE
Do we need all the files in the /js/ folder?

### ISSUE THREAD

**Issue by b-stone** [b-stone/Visualize-M2#31]
I just noticed that we have a lot of files in the `/js/` folder. Are these all needed?

**Comment by bbarwick** [comment]
Most of them can be deleted.  I added a ton of them for the Graphulus 3d graphing example, but I will go through and delete the extraneous ones.

**Comment by b-stone** [comment]
We should make another sweep through these. For example, we don't need both `Three.js` and `three.min.js`. This means we need to go through and make sure all sources are the min versions of the js files.

**Comment by bbarwick** [comment]
I will look back through and see which files we actually need.  We can also minify all of our js files (using something like [http://refresh-sf.com/](http://refresh-sf.com/)) before including them in any sort of release version of the package, and keep non-minified versions on the development branch for easy editing.  I will be making a new branch (cleanup_brett) to try and do lots of cleaning up and organizing.  I won't touch any of the visIdeal stuff since Tom is working on it.

**Comment by bbarwick** [comment]
Also, do we need the server-stuff folder or the jims-tests folder?

**Comment by bbarwick** [comment]
Okay, so after going through and deleting all of the unnecessary stuff (on the cleanup_brett branch), I have the following:

- Necessary files (as far as I can tell):
  - /js/ folder
    - visGraph2d.js
    - visDigraph2d.js
    - visPoset.js
    - visSimplicialComplex2d.js
    - jquery-1.11.3.min.js
    - BootSideMenu.js
    - d3.v3.min.js
    - bootstrap.min.js (used in BootSideMenu.js)
    - clipboard.min.js
    - nouislider.min.js
    - underscore.js (used in the monomial ideal visualization)
  - /css/ folder
    - BootSideMenu.css
    - bootstrap.min.css
    - common.css (I condensed all common CSS styles from the visualization templates to this css file)
    - nouislider.min.css
    - nouislider.tooltips.css (although we never use the tooltips for the sliders, so we can probably delete this)
  - /images/ folder
    - 32px-Octicons-clippy.png

- Stuff I'm not sure whether we need:
  - The entire /fonts/ folder?
  - /js/ folder
    - CSS3DRenderer.js
    - DAT.GUI.min.js
    - Detector.js
    - Detectors.js
    - jquery-ui.js
    - KeyboardState.js
    - OrbitControls.js
    - OrbitControls-Touch.js
    - RequestAnimationFrame.js
  - /css/ folder
    - The /css/images/ folder?
    - base.css
    - bootstrap-theme.min.js
    - index.css
    - info.css
    - jqueryui.css
  - /images/ folder
    - square.png
    - testpic.png
    - The /images/Visualize/ subfolder?

@vlandham If you have time, could you weigh in on whether any of these js files, cs files, or images are being used in the monomial ideal visualization code, or whether they need to be included because of dependencies that you're aware of from other libraries that we are using?

I will try to track some of the Github file histories for some of these files to see whether I added them while I was trying to implement parametric surface visualization.

**Comment by b-stone** [comment]
we do not need the server-stuff or jim's test folders. I like them on the dev branch (master) though.

**Comment by b-stone** [comment]
This is great. I think we should do this on the master as well though.
